baseURL = 'https://aslp-lab.github.io/HumDial-Challenge/'
languageCode = 'en-us'
title = 'ICASSP 2026: Human-like Spoken Dialogue Systems Challenge'
theme = ["hugo-chart", "arcana"]
[menu]

    [[menu.main]]
        identifier = "track1"
        name="Track 1: Emotional Intelligence"
        weight=100
    [[menu.main]]
        identifier ="description_1"
        parent = "track1"
        name = "Description"
        url= "/track1/description"
        weight = 1
    [[menu.main]]
        parent = "track1"
        identifier="test_set_1"
        name = "Test_set"
        url="/track1/test_set"
        weight = 2
    [[menu.main]]
        parent = "track1"
        identifier="results_1"
        name = "Results"
        url="/track1/results"
        weight = 3
    [[menu.main]]
        identifier = "track2"
        name="Track 2: Full-Duplex Interaction"
        weight=110
    [[menu.main]]
        identifier ="description_2"
        parent = "track2"
        name = "Description"
        url= "/track2/description"
        weight = 1
     [[menu.main]]
        parent = "track2"
        identifier="test_set_2"
        name = "Test_set"
        url="/track2/test_set"
        weight = 2
    [[menu.main]]
        parent = "track2"
        identifier="results_2"
        name = "Results"
        url="/track2/results"
        weight = 3


